FROM node:lts-slim as build

WORKDIR /app

COPY ./SocialNetwork.Frontend/ .
## RUN npm init
RUN npm install
RUN npm run build

FROM nginx:latest
COPY --from=build /app/dist/frontend /usr/share/nginx/html
## EXPOSE 80